### ISSUE TITLE
Regression: `background` CSS property on <body> element is not generated with premailer 1.8.7 / css_parser 1.4.5

### ISSUE THREAD

**Issue by ajb** [premailer/premailer#315] opened 2016-08-17 16:45 UTC
First off, thanks to the maintainers for this awesome time-saver of a library, and apologies if this should be filed in the `css_parser` repo -- I'm still unsure where the root cause of this issue is.

We first noticed that our emails were not rendering with the correct background color: 

<img width="822" alt="screen shot 2016-08-17 at 9 42 56 am" src="https://cloud.githubusercontent.com/assets/1270317/17744996/fdc4ba78-645e-11e6-8d48-b864a27745b9.png">

Upon further investigation, we noticed that when we bumped `premailer` and `css_parser`, our `<body>` element was lacking the `background: ...` property in its style attribute.

Here's an isolated test case: https://github.com/ajb/premailer-background-test

Generated with the old versions, premailer 1.8.6 and css_parser 1.4.2:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>

</head>
<body style="background: #ffffff" bgcolor="#ffffff">
<style type="text/css">
body {
background-color: #ffffff;
}
</style>
Hi!
</body>
</html>
```

And with the newest versions, showing the regression:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>

</head>
<body style=";" bgcolor="#ffffff">
<style type="text/css">
body {
background-color: #ffffff;
}
</style>
Hi!
</body>
</html>
```

**Comment by villesundberg** [comment] 2016-08-18 07:24
I ran into this, too. The `bgcolor="#ffffff"` declaration works as a fallback in some cases, but a lot of email clients ignore it when the color is defined with a three-digit shorthand, e.g. `#fff`.

**Comment by villesundberg** [comment] 2016-08-27 09:32
If we set the `css_to_attributes` option to `false`, the `background` property is generated correctly (while we lose the `bgcolor` attribute.)

premailer 1.8.7 and css_parser 1.4.5:

```
source = "<body><style>body { background: #123; }</style></body>"
Premailer.new(source, with_html_string: true, css_to_attributes: false).to_inline_css
```
will generate:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body style="background: #123;"><style type="text/css">
body {
background: #123;
}
</style></body></html>
```

**Comment by villesundberg** [comment] 2016-08-27 09:40
It would seem that this is an intentional change made in d5626eb168756e53c65cf5764fd808dad23f3543.

@janko-m: can you comment on the motivation behind this?

**Comment by janko-m** [comment] 2016-08-27 09:45
@villesundberg I have to say I don't remember 😃. It was introduced in https://github.com/premailer/premailer/pull/267 for fixing https://github.com/premailer/premailer/issues/173.

**Comment by ajb** [comment] 2016-08-29 18:00
Seems like it would have been an unintended side-effect of that change then, no?

**Comment by villesundberg** [comment] 2016-08-29 18:13
Based on the commentary on #267 and #173, it's possible that this is by design, though any explicit cases where the double styling is harmful aren't provided.

That being said I'm fairly certain we should revert to the behavior in 1.8.6 (while keeping the change that `-premailer-` styles don't generate attributes.)

@silvenon: can you remember the motivation?

**Comment by whatcould** [comment] 2016-08-30 16:15
I'm having a related issue — I am trying to specify `float: none` on an `img`, but that gets converted to `align: none` and the CSS gets removed (this is also related to #179). 

I'd vote just removing the `-premailer-` styles and not all of them; I can't think of a scenario in which you'd specify a CSS style and then not want the style to appear, even if it's being duplicated via an attribute for less-capable email clients.

**Comment by wydflannery** [comment] 2016-08-30 17:23
This is also happening to our email templates, the background css attribute is being removed and replaced with bgcolor, causing some weird display issues with Outlook and Gmail when we are overwriting a container background.

**Comment by ajb** [comment] 2016-09-23 02:06
Do any of the maintainers have a preferred solution for this? I'd be more than happy to help with a PR, but I'm not sure where to start.

**Comment by wydflannery** [comment] 2016-09-23 16:07
Not a maintainer but setting the **css_to_attributes** option to false fixed my issue and I didn't notice any other changes when I tested the email template.

**Comment by ajb** [comment] 2016-09-23 16:20
Thanks for the suggestion, but we _do_ use the other `premailer-*` attributes (like `-premailer-cellspacing`, which I think would be disabled by setting `css_to_attributes: false`.

**Comment by fernandobrito** [comment] 2016-11-14 00:19
I'm also negatively affected by the fact that my CSS background-color rule gets converted to bgcolor and then deleted.

Python library `premailer` keeps both the HTML attribute and CSS style: https://github.com/peterbe/premailer#html-attributes-created-additionally. I would vote to have the same behavior here, as I also couldn't think on any case where double styling is harmful.

**Comment by akzhan** [comment] 2017-02-03 22:10
Should be fixed by new property of Premailer initiated by #329.

**Closed by akzhan** 2017-02-03 22:10 UTC

**Comment by t-sakaguchi** [comment] 2021-12-07 08:25
![confirmation_on_create_instructions](https://user-images.githubusercontent.com/55119598/144992937-ac28cdb8-aa1e-436a-b65a-b142f5c3263f.jpg)
確認できました！mailのスタイルはwebpakcerに移し替えたんですね。

**Comment by t-sakaguchi** [comment] 2021-12-07 08:27
[IMO] メールアクションの名前を変更した方が良いと思います。
既存は「有効化のリンク」を送っていますが、新規では削除されていますね。
`confirmation_on_create_instructions` ではない名前に変えたほうが良さそうです。
