### ISSUE TITLE
Inline style with "background-color:" is not getting applied

### ISSUE THREAD

**Issue by sampatbadhe** [premailer/premailer#318] opened 2016-09-16 07:42 UTC
Don't know whether its issue or not.. but can i get help on this?

I am applying background color as gold to table

`<table style="background-color:gold;"></table>`

But its getting removed after email is sent. In email it will removes the complete style tag

`<table></table>`

I Tried with other color like red, blue, yellow, green...etc, it works fine

`<table style="background-color:red;"></table>`

In email it adds background color

`<table style="background:red;"></table>`

Any idea why it removes `background-color` style with `gold, lightcyan, indigo....etc` color is not getting applied?

https://github.com/fphilipe/premailer-rails/issues/172

**Comment by ajb** [comment] 2016-09-23 02:04
Duplicate of https://github.com/premailer/premailer/issues/315?

**Closed** 2023-02-16 01:16 UTC
